version: '2'
services:
  db:
    container_name: scinote_db_production
    image: postgres:15
    volumes:
      - /apps/scinote-web/mounted_data/db:/var/lib/postgresql/data
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=MyVerySecretPassword2023"
    networks:
      - internal
    restart: unless-stopped
  web:
    build:
      context: .
      dockerfile: Dockerfile.production
    image: scinote_web_production
    container_name: scinote_web_production
    stdin_open: true
    env_file: ./production.env
    tty: true
    depends_on:
      - db
    command: bash -c "rm -f /usr/src/app/tmp/pids/server.pid && rails s -b 0.0.0.0"
    environment:
      - RAILS_ENV=production
    volumes:
      - /apps/scinote-web/mounted_data/system:/usr/src/app/public/system
      - /apps/scinote-web/mounted_data/storage:/usr/src/app/storage
    labels:
      - traefik.enable=true
      - traefik.http.routers.scinote_web_production.entrypoints=http
      - traefik.http.routers.scinote_web_production.rule=Host("eln.bellstedt-lab.ch")
      - traefik.http.middlewares.scinote_web_production-https-redirect.redirectscheme.scheme=https
      - traefik.http.routers.scinote_web_production.middlewares=scinote_web_production-https-redirect
      - traefik.http.routers.scinote_web_production-secure.entrypoints=https
      - traefik.http.routers.scinote_web_production-secure.rule=Host("eln.bellstedt-lab.ch")
      - traefik.http.routers.scinote_web_production-secure.tls=true
      - traefik.http.routers.scinote_web_production-secure.tls.certresolver=http
      - traefik.http.services.scinote_web_production.loadbalancer.server.port=3000
      - traefik.docker.network=traefik-proxy
    networks:
      - traefik-proxy
      - internal
    restart: unless-stopped
  jobs:
    image: scinote_web_production
    container_name: scinote_jobs_production
    tty: true
    depends_on:
      - db
    command: rake jobs:work
    env_file: ./production.env
    environment:
      - RAILS_ENV=production
    volumes:
      - /apps/scinote-web/mounted_data/system:/usr/src/app/public/system
      - /apps/scinote-web/mounted_data/storage:/usr/src/app/storage
    networks:
      - internal
    restart: unless-stopped
networks:
  traefik-proxy:
    external: true
  internal:
    internal: true
